# Generated by Django 4.2 on 2023-12-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatabaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(default='null', editable=False, max_length=255)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('d', 'Downloaded'), ('w', 'Watched'), ('r', 'Removed')], default='d', max_length=10)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Matabase',
                'ordering': ('-updatedDate', '-createdDate'),
            },
        ),
    ]
